fix(server_openvr): Force usage of UuidFromStringA()
RPC_CSTR isn't a wide string, so it the A version of UuidFromString()
can be called explicitly.

Fixes this build error with clang-cl 19.1.7
cpp/platform/win32/shared/d3drender.cpp(93,4): error: no matching function for call to 'UuidFromStringW'
     93 |                         UuidFromString( ( RPC_CSTR ) "8c8f13b1-60eb-4b6a-a433-de86104115ac", &guid );
        |                         ^~~~~~~~~~~~~~
  .../kits/10/include/10.0.26100.0/shared/rpcdce.h(2775,24): note: expanded from macro 'UuidFromString'
   2775 | #define UuidFromString UuidFromStringW
        |                        ^~~~~~~~~~~~~~~
  .../kits/10/include/10.0.26100.0/shared/rpcdce.h(2769,1): note: candidate function not viable: no known conversion from 'RPC_CSTR' (aka 'unsigned char *') to 'RPC_WSTR' (aka 'unsigned short *') for 1st argument
   2769 | UuidFromStringW (
        | ^
   2770 |     _In_opt_ RPC_WSTR StringUuid,
        |              ~~~~~~~~~~~~~~~~~~~