fix: Miscellaneous fixups when building with clang-cl (#3116)
* fix(server_openvr): Fix inputColorAdjust type

Fixes this build error with clang-cl 19.1.7
cpp/platform/win32/FrameRender.cpp(787,15): error: non-constant-expression cannot be narrowed from type 'int' to 'uint32_t' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]

* fix(server_openvr): Remove useless D3D9Types.h include

* fix(server_openvr): Normalize Windows link libraries to lowercase for cross-compilation

Standardize all Windows API libraries to use lowercase filenames.
This ensures compatibility when cross-compiling on case-sensitive
filesystems (Linux with MinGW).

* fix(server_openvr): Force usage of UuidFromStringA()

RPC_CSTR isn't a wide string, so it the A version of UuidFromString()
can be called explicitly.

Fixes this build error with clang-cl 19.1.7
cpp/platform/win32/shared/d3drender.cpp(93,4): error: no matching function for call to 'UuidFromStringW'
     93 |                         UuidFromString( ( RPC_CSTR ) "8c8f13b1-60eb-4b6a-a433-de86104115ac", &guid );
        |                         ^~~~~~~~~~~~~~
  .../kits/10/include/10.0.26100.0/shared/rpcdce.h(2775,24): note: expanded from macro 'UuidFromString'
   2775 | #define UuidFromString UuidFromStringW
        |                        ^~~~~~~~~~~~~~~
  .../kits/10/include/10.0.26100.0/shared/rpcdce.h(2769,1): note: candidate function not viable: no known conversion from 'RPC_CSTR' (aka 'unsigned char *') to 'RPC_WSTR' (aka 'unsigned short *') for 1st argument
   2769 | UuidFromStringW (
        | ^
   2770 |     _In_opt_ RPC_WSTR StringUuid,
        |              ~~~~~~~~~~~~~~~~~~~

(cherry picked from commit aa724975a2b70bc3e00e268de447c9f85ed62ceb)